name: urban_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_secure_storage: ^8.0.0
  dio: ^5.1.1
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  string_validator: ^1.0.0
  badges: ^3.0.3
  flutter_screenutil: ^5.7.0
  lottie: ^2.3.1
  loading_animation_widget: ^1.2.0+4
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  firebase_auth: ^4.4.2
  awesome_notifications: ^0.7.4+1
  url_launcher: ^6.1.10
  intl: ^0.17.0
  pin_code_fields: ^7.4.0
  custom_timer: ^0.1.2
  cloud_firestore: ^4.5.2
  another_stepper: ^1.2.2
  flutter_switch: ^0.3.2
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  focused_menu_custom: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.13.1
  firebase_messaging_platform_interface: ^4.3.0
  change_app_package_name: ^1.1.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/urban_app_icon.png"
  min_sdk_android: 21

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/animations/
    - assets/logos/
    - assets/fonts/

  fonts:
    - family: bahij
      fonts:
        - asset: assets/fonts/bahij_regular.ttf


